### ISSUE TITLE
Question concerning silent SMS

### ISSUE THREAD

**Issue by cliebig2019** [MatejKovacic/silent-sms-ping#14]
Hello,
I just came across your repo and wondered how silent SMS are sent.
As far as I see the SmsManager class is used to send SMS, however there the pid according to my knowledge so far cannot be set within the SMS, which is crucial to send a silent SMS.
Am I missing something?
Thanks

**Comment by MatejKovacic** [comment]
Yes, there are several types of SMS. This app can handle only one.
