### ISSUE TITLE
apk does not insrall

### ISSUE THREAD

**Issue by StephanBusch** [MatejKovacic/silent-sms-ping#8]
the provided .apk from april 23th does not install on my Note 9. The package installer shows an error message that there is a problem parsing the package.

**Comment by stefanb** [comment]
How was this fixed? I also get this error and can not install the [provided latest silent-sms-app-debug_22-04-2023.apk](https://github.com/MatejKovacic/silent-sms-ping/blob/master/silent-sms-app-debug_22-04-2023.apk) on Android 11.

I prepared a possible fix in #12
